FROM python:3.10-slim
WORKDIR /app
COPY backend/ /app/backend/
COPY requirements.txt /app/requirements.txt
RUN apt-get update && apt-get install -y build-essential libgl1 && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r /app/requirements.txt
EXPOSE 8000
CMD ["uvicorn","backend.main:app","--host","0.0.0.0","--port","8000","--reload"]

