# examples/train_lora/finscribe_lora_sft.yaml
# LLaMA-Factory SFT configuration for FinScribe invoice validation/correction
# Usage: llamafactory-cli train examples/train_lora/finscribe_lora_sft.yaml

model_name_or_path: <MODEL_NAME_OR_PATH>    # e.g. meta-llama/Meta-Llama-3-8B-Instruct or any supported small model
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
dataset: finscribe_unsloth
template: default
cutoff_len: 1024
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 4

output_dir: saves/finscribe/lora/sft
logging_steps: 10
save_steps: 200
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false           # set true if hardware supports it
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200

