import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// HF Space API endpoint for PaddlePaddle/doc2page
const DOC2PAGE_API_URL = "https://paddlepaddle-doc2page.hf.space/api/predict";

interface Doc2PageResult {
  success: boolean;
  html?: string;
  pages?: string[];
  error?: string;
  usedFallback: boolean;
  model: string;
}

async function callDoc2PageAPI(imageBase64: string, hfToken: string): Promise<string> {
  // Try calling the Gradio Space API
  const response = await fetch(DOC2PAGE_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${hfToken}`,
    },
    body: JSON.stringify({
      data: [`data:image/jpeg;base64,${imageBase64}`]
    }),
  });

  if (!response.ok) {
    throw new Error(`HF API returned ${response.status}: ${await response.text()}`);
  }

  const result = await response.json();
  console.log("Doc2Page raw response:", JSON.stringify(result).substring(0, 500));

  // Parse various response formats from Gradio
  if (result.data && Array.isArray(result.data) && result.data[0]) {
    return result.data[0];
  }
  if (result.html) {
    return result.html;
  }
  if (result.output) {
    return result.output;
  }
  
  throw new Error("Unexpected response format from Doc2Page");
}

function generateMockHtmlPage(imageBase64: string): string {
  const timestamp = new Date().toLocaleString();
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Doc2Page - Document Preview</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
      min-height: 100vh;
      padding: 20px;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 24px;
      text-align: center;
    }
    .header h1 { font-size: 28px; margin-bottom: 8px; }
    .header p { opacity: 0.9; font-size: 14px; }
    .content { padding: 24px; }
    .document-preview {
      border: 2px dashed #e2e8f0;
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 20px;
      background: #f8fafc;
    }
    .document-preview img {
      width: 100%;
      height: auto;
      border-radius: 8px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    .watermark {
      background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
      color: white;
      padding: 16px;
      text-align: center;
      font-weight: 600;
    }
    .meta {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
      margin-top: 20px;
    }
    .meta-card {
      background: #f1f5f9;
      padding: 16px;
      border-radius: 8px;
    }
    .meta-card h3 { font-size: 12px; color: #64748b; text-transform: uppercase; margin-bottom: 4px; }
    .meta-card p { font-size: 16px; color: #1e293b; font-weight: 500; }
    .footer {
      background: #1e293b;
      color: white;
      padding: 16px;
      text-align: center;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📄 Document Processed</h1>
      <p>Powered by ERNIE & PaddleOCR: Doc2Page</p>
    </div>
    
    <div class="watermark">
      ✨ Processed with ERNIE • PaddleOCR: Doc2Page
    </div>
    
    <div class="content">
      <div class="document-preview">
        <img src="data:image/jpeg;base64,${imageBase64}" alt="Uploaded Document" />
      </div>
      
      <div class="meta">
        <div class="meta-card">
          <h3>Processing Engine</h3>
          <p>PaddleOCR Doc2Page</p>
        </div>
        <div class="meta-card">
          <h3>Processed At</h3>
          <p>${timestamp}</p>
        </div>
        <div class="meta-card">
          <h3>Status</h3>
          <p>✅ Complete</p>
        </div>
        <div class="meta-card">
          <h3>Format</h3>
          <p>HTML Document</p>
        </div>
      </div>
    </div>
    
    <div class="footer">
      <p>Generated by FinScribe • ERNIE & PaddleOCR: Doc2Page</p>
      <p style="margin-top: 8px; opacity: 0.7;">https://huggingface.co/spaces/PaddlePaddle/doc2page</p>
    </div>
  </div>
</body>
</html>`;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageBase64, fileName } = await req.json();
    
    if (!imageBase64) {
      return new Response(
        JSON.stringify({ success: false, error: 'No image data provided' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const hfToken = Deno.env.get('HUGGING_FACE_ACCESS_TOKEN');
    let result: Doc2PageResult;

    try {
      if (hfToken) {
        console.log("Calling Doc2Page HF Space API...");
        const html = await callDoc2PageAPI(imageBase64, hfToken);
        result = {
          success: true,
          html,
          pages: [html],
          usedFallback: false,
          model: 'PaddlePaddle/doc2page'
        };
      } else {
        throw new Error("No HF token configured");
      }
    } catch (apiError) {
      console.warn("Doc2Page API failed, using fallback:", apiError);
      
      // Generate mock HTML page with watermarks
      const mockHtml = generateMockHtmlPage(imageBase64);
      
      result = {
        success: true,
        html: mockHtml,
        pages: [mockHtml],
        usedFallback: true,
        model: 'mock-fallback'
      };
    }

    return new Response(
      JSON.stringify(result),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Doc2Page error:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error instanceof Error ? error.message : 'Unknown error' 
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
